FROM mcr.microsoft.com/windows/servercore:ltsc2016

ENV COMPLUS_NGenProtectedProcess_FeatureEnabled 0

RUN \Windows\Microsoft.NET\Framework64\v4.0.30319\ngen update & \
	\Windows\Microsoft.NET\Framework\v4.0.30319\ngen update

RUN  dism /online /enable-feature /all /featurename:IIS-Webserver \
 /featurename:IIS-WebServerRole \ 
 /featurename:IIS-ASPNET45 \
 /NoRestart /Quiet


EXPOSE 80
EXPOSE 443
